import React, { useEffect, useState } from "react";
import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";
import MobileMenu from "./MobileMenu";
import { connect } from "react-redux";
import { getMyprofile } from "../../redux/action/apis/auth/profile/getProfile";
import { GetAllChats } from "../../redux/action/apis/realTime/chat/chats";
import { GetNotifications } from "../../redux/action/apis/realTime/notification/getAllNotification";
import { GetSavedBoard } from "../../redux/action/apis/savedProject/boardProjects/getone";
import { GetBoards } from "../../redux/action/apis/savedProject/board/get";

const Layout = ({
    children,
    shortheader,
    isbodyWhite,
    headerStyle,
    showTabs = true,
    iSsticky = true,
    getMyprofile,
    GetAllChats,
    GetNotifications,
    login_respond,
    GetBoards

}) => {
    const [isToggled, setToggled] = useState(1);


    const toggleClick = (type) => {
        setToggled(type);
        isToggled > 1
            ? document
                .querySelector("body")
                .classList.remove("mobile-menu-active")
            : document
                .querySelector("body")
                .classList.add("mobile-menu-active");
    };


    useEffect(() => {
        getMyprofile()              // create a day sessions
        GetBoards({})
        GetAllChats()
        GetNotifications()
    }, [login_respond])
    return (
        <>
            <Head>
                <title>{"hader of duvdu"}</title>
                <meta name="description" content={"Generated by create Ahmed Magdy"} />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {isToggled && <div className="body-overlay-1" onClick={toggleClick}></div>}

            <Header headerStyle={headerStyle} isToggled={isToggled} toggleClick={toggleClick} fromlayout={{ shortheader: shortheader, iswhite: isbodyWhite, showTabs: showTabs, iSsticky: iSsticky }} />

            <MobileMenu isToggled={isToggled} toggleClick={toggleClick} />

            <main className="main bg-body" >
                {children}
            </main>
            {/* <Footer /> */}
        </>
    );
};
const mapStateToProps = (state) => ({
    login_respond: state.api.login,
});

const mapDispatchToProps = {
    getMyprofile,
    GetAllChats,
    GetNotifications,
    GetBoards

};
export default connect(mapStateToProps, mapDispatchToProps)(Layout);
