import React, { useState } from "react";
import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";
import MobileMenu from "./MobileMenu";

const Layout = ({
    children,
    shortlayout,
    isbodyWhite,
    headerStyle,
}) => {
    const [isToggled, setToggled] = useState(false);


    const toggleClick = () => {
        setToggled(!isToggled);
        isToggled
            ? document
                .querySelector("body")
                .classList.remove("mobile-menu-active")
            : document
                .querySelector("body")
                .classList.add("mobile-menu-active");
    };

    return (
        <>
            <Head>
                <title>{"header must be here"}</title>
                <meta name="description" content={"Generated by create Ahmed Magdy"} />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {isToggled && <div className="body-overlay-1" onClick={toggleClick}></div>}

            <Header headerStyle={headerStyle} isToggled={isToggled} toggleClick={toggleClick} fromlayout={{ shortlayout: shortlayout, iswhite: isbodyWhite }} />

            <MobileMenu isToggled={isToggled} toggleClick={toggleClick} />

            <main className="main bg-body" >
                {children}
            </main>
            {/* <Footer /> */}
        </>
    );
};

export default Layout;
