import React, { useEffect, useState } from 'react';
import { connect } from "react-redux";
import { GetTerms } from '../redux/action/apis/terms/getterms';
import Layout from '../components/layout/Layout';

const htmlTerms = `<p>This Terms &amp; Conditions describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.<br>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a target="_blank" rel="noopener noreferrer" href="https://example.com">Free Privacy Policy Generator</a>.<br>Interpretation and Definitions<br>Interpretation<br>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.<br>Definitions<br>For the purposes of this Privacy Policy:</p>
<ul>
    <li>Account means a unique account created for You to access our Service or parts of our Service.</li>
    <li>Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
    <li>Application refers to Duvdu, the software program provided by the Company.</li>
    <li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Duvdu.</li>
    <li>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
    <li>Country refers to: Egypt</li>
    <li>Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
    <li>Personal Data is any information that relates to an identified or identifiable individual.</li>
    <li>Service refers to the Application or the Website or both.</li>
    <li>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
    <li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
    <li>Website refers to Duvdu, accessible from <a target="_blank" rel="noopener noreferrer" href="https://www.duvdu.com">www.duvdu.com</a></li>
    <li>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
</ul>
<p>Collecting and Using Your Personal Data<br>Types of Data Collected</p>
`

const Page = ({ api, GetTerms , respond }) => {
    const [terms, setTerms] = useState('');
    useEffect(() => {
        GetTerms()
    }, [])
    useEffect(() => {
        if(respond)
            setTerms(respond.data.desc)
    }, [respond?.message])
    
    return (

        <Layout>
            <div className='container py-10'>

                <h1 className='text-3xl font-medium'>
                    Terms & Conditions

                </h1>
                <span className='opacity-80 text-xs'>
                    Last updated: December 22, 2023
                </span>

                <section className='termsBody mt-8 text-lg font-medium' dangerouslySetInnerHTML={{ __html: terms }} />
            </div>
        </Layout>
    );
};

const mapStateToProps = (state) => ({
    api: state.api,
    respond: state.api.GetTerms
});

const mapDispatchToProps = {
    GetTerms
};

export default connect(mapStateToProps, mapDispatchToProps)(Page);

