// ADD FORM TYPES

export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA';
export const INSERT_TO_ARRAY = 'INSERT_TO_ARRAY';
export const REMOVE_ITEM_FROM_FIELD = 'REMOVE_ITEM_FROM_FIELD';
export const SET_ERRORS = 'SET_ERRORS';
export const RESET_FORM = 'RESET_FORM';
export const SET_ATTACHMENTS = 'SET_ATTACHMENTS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_POST_SUCCESS = 'SET_POST_SUCCESS';
export const SET_SUBMITT = 'SET_SUBMITT';
