import React, { useEffect, useState } from "react";
import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";
import MobileMenu from "./MobileMenu";
import { connect } from "react-redux";
import { getMyprofile } from "../../redux/action/apis/auth/profile/getProfile";
import { GetAllChats } from "../../redux/action/apis/realTime/chat/chats";
import { GetNotifications, cleanupSocket } from "../../redux/action/apis/realTime/notification/getAllNotification";
import { GetBoards } from "../../redux/action/apis/savedProject/board/get";
import { GetFavList } from "../../redux/action/apis/savedProject/fav/getAll";
import { getCategory } from "../../redux/action/apis/category/getCategories";
import { init } from "../../redux/action/apis/init/getdata";
import { useRouter } from "next/router";
import { LogOut } from "../../redux/action/apis/auth/logout";
import Chat from "../elements/chat";
import ErrorAndLoadingHandling from "./assets/errorAndLoadingHandling";
import RegistrationRequired from "../popsup/booking/registrationRequired";
import TestOTPCode from "../popsup/testOTPCode";
import GoogleAnalytics from "../GoogleAnalytics";



const Layout = ({
    user,
    children,
    shortheader,
    isbodyWhite,
    headerStyle,
    showTabs = true,
    iSsticky = true,
    getMyprofile,
    GetAllChats,
    GetNotifications,
    GetBoards,
    GetFavList,
    getCategory,
    GetBoards_respond,
    GetAllChats_respond,
    GetNotifications_respond,
    GetFavList_respond,
    getCategory_respond,
    logout_respond,
    LogOut,
    cleanupSocket,
    init

}) => {
    const [isToggled, setToggled] = useState(1);
    const router = useRouter();
    

    const toggleClick = (type) => {
        setToggled(type);
        isToggled > 1
            ? document
                .querySelector("body")
                .classList.remove("mobile-menu-active")
            : document
                .querySelector("body")
                .classList.add("mobile-menu-active");
    };

    useEffect(() => {
        if (!getCategory_respond)
            getCategory()
    }, [getCategory_respond])

    useEffect(() => {
        if (!user)
            getMyprofile()
    }, [user])

    useEffect(() => {
        init()
    }, [])

    useEffect(() => {
        if (user?.username) {
            if (!GetBoards_respond)
                GetBoards({})
            if (!GetFavList_respond)
                GetFavList({})
            if (!GetAllChats_respond)
                GetAllChats()
            if (!GetNotifications_respond) {
                GetNotifications()
            }
        }
        return () => {
            // cleanupSocket();
        };
    }, [user?.username])

    useEffect(() => {
        if(logout_respond?.data) {
            router.push({
            pathname: "/login",
        });
        LogOut(-1)
    }
    }, [logout_respond]);

    return (
        <>
            
            <Head>
                <title>{"hader of duvdu"}</title>
                <meta name="description" content={"Generated by Ahmed Magdy"} />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Chat/>
            <ErrorAndLoadingHandling/>
            <RegistrationRequired/>
            <TestOTPCode/>
            {/* {isToggled && <div className="body-overlay-1" onClick={toggleClick}></div>} */}

            <Header headerStyle={headerStyle} isToggled={isToggled} toggleClick={toggleClick} fromlayout={{ shortheader: shortheader, iswhite: isbodyWhite, showTabs: showTabs, iSsticky: iSsticky }} />

            <MobileMenu isToggled={isToggled} toggleClick={toggleClick} />

            <main className="main bg-body" >
                {children}
            </main>
            <GoogleAnalytics ga_id="G-L1SQRZGHZB" />
            
            {/* <Footer /> */}
        </>
    );
};
const mapStateToProps = (state) => ({
    user: state.auth.user,
    login_respond: state.api.login,
    getMyprofile_respond: state.api.getMyprofile,
    categories: state.categories,

    GetAllChats_respond: state.api.GetAllChats,
    GetNotifications_respond: state.api.GetNotifications,
    GetBoards_respond: state.api.GetBoards,
    GetFavList_respond: state.api.GetFavList,
    logout_respond: state.api.LogOut,
    getCategory_respond: state.api.getCategory,
});

const mapDispatchToProps = {
    getMyprofile,
    GetAllChats,
    GetNotifications,
    cleanupSocket,
    GetBoards,
    GetFavList,
    LogOut,
    init,
    getCategory

};
export default connect(mapStateToProps, mapDispatchToProps)(Layout);
