
// PROJECT TYPES

export const ADD_PROJECT = "ADD_PROJECT"
export const DELETE_PROJECT = "DELETE_PROJECT"
export const UPDATE_PROJECT = "UPDATE_PROJECT"
export const FETCHED_PROJECT = "FETCHED_PROJECT"
export const FETCHED_MORE_PROJECT = "FETCHED_MORE_PROJECT"
export const UPDATE_PROJECT_FILTERS = "UPDATE_PROJECT_FILTERS"
export const UPDATE_PROJECT_CATEGORY = "UPDATE_PROJECT_CATEGORY"
export const UPDATE_RATING = "UPDATE_RATING"

// SETTING TYPES

export const DARK = "DARK"
export const LIGHT = "LIGHT"
export const LANGUAGE = "LANGUAGE"
export const NONEPOPUP = "NONEPOPUP"
export const SHOWNOTOFICATION = "SHOWNOTOFICATION"
export const SHOWSETTING = "SHOWSETTING"
export const SHOWPROFILE = "SHOWPROFILE"

// SETTING AUTH

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER = 'SET_USER';
export const USER_NONE = 'USER_NONE';
export const PERMITTED = "PERMITTED"
export const DENIED = "DENIED"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"



// PROFILE
export const SET_PROFILE_DATE = 'SET_PROFILE_DATE';

// LOCAL STORAGE
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';