
// PROJECT TYPES

export const ADD_PROJECT = "ADD_PROJECT"
export const DELETE_PROJECT = "DELETE_PROJECT"
export const UPDATE_PROJECT = "UPDATE_PROJECT"
export const FETCHED_PROJECT = "FETCHED_PROJECT"
export const FETCHED_MORE_PROJECT = "FETCHED_MORE_PROJECT"

// SETTING TYPES

export const DARK = "DARK"
export const LIGHT = "LIGHT"
export const LANGUAGE = "LANGUAGE"
export const NONEPOPUP = "NONEPOPUP"
export const SHOWNOTOFICATION = "SHOWNOTOFICATION"
export const SHOWSETTING = "SHOWSETTING"
export const SHOWPROFILE = "SHOWPROFILE"

// SETTING AUTH
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"


// LOCAL STORAGE
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';