
// PROJECT TYPES
export const FETCHED_PROJECT = "FETCHED_PROJECT"
export const ADD_PROJECT = "ADD_PROJECT"
export const DELETE_PROJECT = "DELETE_PROJECT"
export const UPDATE_PROJECT = "UPDATE_PROJECT"
export const FETCHED_MORE_PROJECT = "FETCHED_MORE_PROJECT"

// MODE color
export const TOGGLE_MODE = "TOGGLE_MODE"


